// import divideByTwo from "./Bit Manipulation/divide by two";
// import isEven from "./Bit Manipulation/01. isEven";
// import isOdd from "./Bit Manipulation/01.isOdd";
// import isPositive from "./Bit Manipulation/isPositive";
// import multiply from "./Bit Manipulation/multiply";
// import multiplyByTwo from "./Bit Manipulation/Multiply By Two";
// import switchSign from "./Bit Manipulation/switchSign";
// import getSingle from "./Bit Manipulation/09. unique-elements-even";
// import getUniqueElement from "./Bit Manipulation/10. unique-element";
// import signChange from "./Bit Manipulation/11. signChnage";
// import detectOppositeSign from "./Bit Manipulation/12. oppositeSign.js";
// import addOne from "./Bit Manipulation/13. addOne";
// import multiplyWith3Point5 from "./Bit Manipulation/14. multiplyWith3Point5";
// // import "./Bit Manipulation/00. basic";
